<?php

namespace ViewBundle\Repository;

/**
 * ChatDiversRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatDiversRepository extends \Doctrine\ORM\EntityRepository
{
}
