user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

publication:
    resource: "@PublicationBundle/Controller/"
    type:     annotation
    prefix:   /

view:
    resource: "@ViewBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"