services:
  app_user.registration.form.type:
    class: UserBundle\Form\Type\RegistrationFormType
    tags:
    - { name: form.type, alias: app_user_registration }
  form_type_user_update:
    class: UserBundle\Form\Type\UserUpdateType
    arguments:
      - '@security.authorization_checker'
    tags:
    - { name: form.type, alias: form_type_user_update }
  app.profile.form.type:
    class: UserBundle\Form\ProfileFormType
    arguments:
    - %fos_user.model.user.class%
    tags:
    - { name: form.type, alias: fluedis_user_profile }
