services:
    country.provider:
        class: AppBundle\Service\CountryProvider
        arguments:
          - AppBundle\Entity\Country
    upload.files:
        class: AppBundle\Service\UploadFiles
        arguments:
            - '%images_directory%'
            - '%files_directory%'
    app.pagination:
        class: AppBundle\Service\Pagination
        arguments:
            - '@request_stack'
            - '@knp_paginator'
